name: ${project.name}
description: ${project.description}
version: ${project.version}

author: arboriginal
website: https://www.spigotmc.org/resources/${spigot-id}/
dev-url: https://github.com/arboriginal/${project.artifactId}

main: ${project.groupId}.${project.artifactId}.${spigo-main}
api-version: ${spigot-api}

depend: [ ]
softdepend: [ ]
database: true

commands:
  tc-reload:
    description: Reload TidyingChest configuration
    permission: tc.reload

permissions:
  tc.reload:
    description: Allows to reload the configuration.
    default: op

  tc.create:
    description: Allows to create a tidying chest.
    default: true

  tc.create.show_loc: # Require tc.create permission
    description: Allows to get existing chests coords when trying to create one
    default: true
    # (this is used when limit is reached of same item target already exists)

  tc.create.ROOT.unlimited: # Require tc.create permission
    description: No limitation for root signs.
    default: false
  # You can use tc.create.ROOT.<limitation-name>, see config.yml
  tc.create.ROOT.default:
    description: Use « default » limit for root signs.
    default: true

  tc.create.TARGET.unlimited: # Require tc.create permission
    description: No limitation for target signs.
    default: false
  # You can use tc.create.TARGET.<limitation-name>, see config.yml
  tc.create.TARGET.default:
    description: Use « default » limit for target signs.
    default: true

  tc.create.ROOT.world.*: # Require tc.create permission
    description: Allows to create root signs in any world
    default: true
  # You can use tc.create.ROOT.world.<world-name>
  # (then remove tc.create.ROOT.world.* permission to your player)

  tc.create.TARGET.world.*: # Require tc.create permission
    description: Allows to create target signs in any world
    default: true
  # You can use tc.create.TARGET.world.<world-name>
  # (then remove tc.create.TARGET.world.* permission to your player)